[workspace]
members=[
"nlp","evol", "dsp", "app", "materials",
]
#[package]
#name = "ml"
#version = "0.1.0"
#authors = ["Chris P <chrisp1877@gmail.com>"]
#edition = "2018"

## See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[dependencies]
#tensorflow = { version = "0.15.0", features = ["tensorflow_gpu"] }


[alias]
t="test -- --nocapture"
nc="-- --nocapture"
